name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04  # Using older Ubuntu for better compatibility
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Cache buildozer global directory
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Install minimal system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-8-jdk \
          python3-pip python3-distutils \
          build-essential cmake \
          zlib1g-dev libffi-dev libssl-dev

    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV

    - name: Install buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer==1.5.0 cython

    - name: Build APK
      run: |
        buildozer android clean
        buildozer -v android debug

    - name: List generated files
      run: |
        echo "Contents of bin directory:"
        ls -la bin/ 2>/dev/null || echo "No bin directory found"
        find . -name "*.apk" -type f 2>/dev/null || echo "No APK files found"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: android-apk
        path: bin/*.apk
        retention-days: 30
